name: builder

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x    
        
    - name: Restore dependencies
      run: dotnet restore     
        
    - name: Test
      run: dotnet test "Calculator/TestProjectCalculator/TestProjectCalculator.csproj" --no-restore --verbosity normal
